var FAQ_ANSWERS = {
    english: {
        "How do I register as a new voter in India?": "You can register online through the Voters' Service Portal (voters.eci.gov.in) or the Voter Helpline App. Alternatively, you can submit a physical copy of Form 6 to the Electoral Registration Officer (ERO) or Booth Level Officer (BLO) of your area. 📝",
        "What is Form 6 and when is it used?": "Form 6 is the application form for 'Registration as a New Voter.' It is used by first-time voters (who have turned 18) or by those shifting their residence from one constituency to another to get their name included in the electoral roll. 🏠",
        "How to track my Voter ID application status?": "Visit the Voters' Service Portal or use the Voter Helpline App and click on 'Track Application Status.' You will need to enter the Reference ID provided to you when you submitted your application. 🔍",
        "What is the deadline for registration before an election?": "The electoral roll is updated continuously, but for a specific election, the deadline is typically the date of the announcement of the election or up to the last date of filing nominations by candidates (usually around 3-4 weeks before polling day). ⏳",
        "How to fill Form 8 for correction of details?": "Form 8 is used for 'Correction of entries in existing electoral roll.' You can fill it online or offline by providing your current EPIC number and attaching supporting documents (like Aadhaar, Birth Certificate, or Utility Bills) for the specific details you wish to correct. ✏️",
        "What is Form 7 and who should fill it?": "Form 7 is used for 'Objection to inclusion or for deletion of a name' in the electoral roll. It is filled by a person who wants to remove their own name (due to shifting) or by someone objecting to the inclusion of a deceased or disqualified person's name. ❌",
        "What is an EPIC number and where can I find it?": "EPIC stands for Elector's Photo Identity Card number. It is a unique 10-digit alphanumeric code printed on the front of your Voter ID card. You can also find it by searching your name on the National Voters' Service Portal (NVSP). 🆔",
        "I lost my Voter ID card. How do I get a duplicate one?": "You should apply using Form 8 (choose the option for 'Replacement of EPIC without correction'). While there is no fee if the card is lost due to natural disasters, a small fee may be charged for a replacement due to negligence or loss. 💳",
        "How can I download my e-EPIC (digital voter card)?": "Log in to the Voters' Service Portal, click on 'Download e-EPIC,' and enter your EPIC number or Form Reference ID. You will receive an OTP on your registered mobile number to verify and download the PDF. 📱",
        "Can I have more than one Voter ID card?": "No. Registering as a voter in more than one place or having multiple Voter IDs is a punishable offense under the Representation of the People Act. If you move, you must transfer your registration using Form 8 or delete the old one using Form 7. 🚫",
        "What IDs are valid for voting if I don't have a physical Voter ID?": "If your name is in the electoral roll, you can vote using any of the 12 alternative photo ID documents approved by the ECI, including: Aadhaar Card, PAN Card, Driving License, Passport, MGNREGA Job Card, and Passbook with photo (Bank/Post Office). 🪪",
        "Can I use my Aadhaar card as ID to vote?": "Yes. An Aadhaar card is an officially accepted alternative photo ID for voting, provided your name is already registered in the official Electoral Roll. 💳",
        "What is the minimum age to be eligible to vote?": "The minimum age is 18 years. You can apply for registration if you are 17+ so that your name is added as soon as you turn 18 on any of the four qualifying dates (Jan 1, April 1, July 1, Oct 1). 🎂",
        "Can NRIs (Non-Resident Indians) vote?": "Yes. NRIs can register as 'Overseas Electors' using Form 6A. However, they must be physically present at their designated polling station in India on the day of voting to cast their vote. ✈️",
        "Can a non-citizen of India vote?": "No. Only citizens of India who are 18 years or older and not otherwise disqualified are eligible to vote. 🇮🇳",
        "How do I find my assigned polling booth?": "You can find your booth by visiting the ECI 'Know Your Polling Station' web page, using the Voter Helpline App, or by sending an SMS with 'ECI <EPIC Number>' to 1950. 📍",
        "What are the standard voting hours on polling day?": "Voting hours generally run from 7:00 AM to 6:00 PM. These timings may vary slightly depending on the constituency and the Election Commission's specific notification for that phase. ⏰",
        "What is the process inside the polling station?": "1. First Polling Officer: Checks your name on the electoral roll and ID. 2. Second Polling Officer: Marks your finger with indelible ink, gives you a slip, and takes your signature. 3. Third Polling Officer: Takes the slip and enables the EVM. 4. Voting Compartment: You press the button on the EVM next to your candidate's symbol. 🗳️",
        "What is the 'Indelible Ink' and why is it used?": "It is a silver nitrate-based purple ink applied to the left forefinger. It is used to prevent multiple voting (voter fraud) as it does not wash off easily and remains visible for several weeks. ☝️",
        "What is an EVM and how does it work?": "An Electronic Voting Machine (EVM) consists of two units: a Control Unit (with the officer) and a Balloting Unit (in the voting compartment). When the officer releases a vote, the voter presses a button on the Balloting Unit to record their choice electronically. 🗳️",
        "What is VVPAT and how does it verify my vote?": "Voter Verifiable Paper Audit Trail (VVPAT) is a machine attached to the EVM. When you vote, it prints a slip showing the serial number, name, and symbol of the candidate you chose. This slip is visible behind a glass window for 7 seconds before falling into a sealed box. ✅",
        "How do I confirm my vote went to the right candidate on the EVM?": "After pressing the button, a red light glows next to the candidate's symbol on the EVM, a loud beep is heard, and the VVPAT screen displays the slip with your chosen candidate's details for 7 seconds. 🧐",
        "What happens if the EVM malfunctions during voting?": "The polling process is halted immediately. The sector officer or technical engineer is called to inspect it. If it cannot be fixed, the entire EVM set (Control Unit, Balloting Unit, and VVPAT) is replaced with a new one, and voting resumes. 🛠️",
        "What is NOTA (None Of The Above)?": "NOTA is an option on the EVM that allows a voter to officially register a vote of 'no confidence' in all the candidates contesting in that constituency. 🚫",
        "How can government employees on election duty vote?": "They can vote via Postal Ballot or an Election Duty Certificate (EDC). Postal ballots are mailed to the returning officer, while an EDC allows them to vote at the polling station where they are performing their duty (if it is in the same constituency). ✉️",
        "What is a 'Tendered Vote'?": "If a person discovers someone else has already voted in their name, they can cast a Tendered Vote. This is done on a physical ballot paper (not the EVM) after the Polling Officer is satisfied with the person's identity. 📄",
        "What is a 'Challenged Vote'?": "If a Polling Agent doubts a voter's identity, they can 'challenge' it by depositing a small fee. The Presiding Officer then holds a summary inquiry by checking the voter's documents. If the challenge is proved, the voter is handed over to the police; if not, the voter is allowed to vote. ⚖️",
        "Is there a facility for senior citizens to vote from home?": "Yes. The ECI provides a Postal Ballot facility for 'Absentee Voters,' which includes senior citizens (above 85 years) and Persons with Disabilities (PwD). They must fill out Form 12D within five days of the election notification to avail of this. 🏡",
        "How are the votes counted and results declared?": "Votes are counted at a centralized counting center under high security. The Control Units of EVMs are brought out, and the totals for each candidate are recorded round by round. The candidate with the highest number of votes is declared the winner by the Returning Officer (RO). 📊",
        "Where can I find real-time results on counting day?": "Real-time results are updated on the official ECI Results website (results.eci.gov.in) and the Voter Helpline App. They are also broadcasted across all major news channels. 📱"
    },
    hindi: {
        "नए मतदाता के रूप में पंजीकरण कैसे करें?": "वोटर्स सर्विस पोर्टल (voters.eci.gov.in) पर ऑनलाइन पंजीकरण करें। फॉर्म 6 भरें और फोटो, आयु व निवास प्रमाण अपलोड करें। 📝",
        "फॉर्म 6 क्या है?": "फॉर्म 6 'नए मतदाता पंजीकरण' के लिए है। इसका उपयोग तब करें जब आप 18+ हों या किसी नए निर्वाचन क्षेत्र में चले गए हों। 🏠",
        "वोटर आईडी आवेदन की स्थिति?": "voters.eci.gov.in पर जाएं और रेफरेंस आईडी का उपयोग करके 'आवेदन की स्थिति ट्रैक करें' पर क्लिक करें। 🔍",
        "चुनाव से पहले पंजीकरण की समय सीमा?": "आमतौर पर, आप चुनाव की घोषणा तक पंजीकरण कर सकते हैं। सटीक समय सीमा के लिए चुनाव कार्यक्रम देखें। ⏳",
        "विवरण सुधारने के लिए फॉर्म 8?": "फॉर्म 8 'सुधार' के लिए है। इसका उपयोग नाम, आयु या पते की गलतियों को ठीक करने के लिए करें। ✏️",
        "फॉर्म 7 क्या है?": "फॉर्म 7 मतदाता सूची से नाम हटाने या आपत्ति के लिए है। ❌",
        "EPIC नंबर क्या है?": "EPIC आपकी विशिष्ट 10-अंकों वाली वोटर आईडी संख्या है, जो आपके कार्ड के सामने फोटो के ऊपर होती है। 🆔",
        "वोटर आईडी खो गया?": "voters.eci.gov.in पर फॉर्म 8 के माध्यम से डुप्लीकेट कार्ड के लिए आवेदन करें। 💳",
        "अपना ई-एपिक कैसे डाउनलोड करें?": "यदि आपका मोबाइल नंबर पंजीकृत है, तो आप पोर्टल से डिजिटल वोटर आईडी (PDF) डाउनलोड कर सकते हैं। 📱",
        "क्या एक से अधिक वोटर आईडी हो सकते हैं?": "नहीं, एक से अधिक वोटर आईडी रखना अवैध है। 🚫",
        "वोटर आईडी के बिना कौन से आईडी मान्य हैं?": "आप आधार, पैन, पासपोर्ट, ड्राइविंग लाइसेंस सहित 12 वैकल्पिक दस्तावेजों का उपयोग कर सकते हैं। 🪪",
        "क्या आधार कार्ड मान्य है?": "हाँ, आधार कार्ड मतदान के लिए स्वीकृत 12 वैकल्पिक फोटो आईडी में से एक है। 💳",
        "वोट देने की न्यूनतम आयु?": "आवेदन के लिए आपकी आयु 18 वर्ष होनी चाहिए। 🎂",
        "क्या एनआरआई वोट दे सकते हैं?": "हाँ, एनआरआई फॉर्म 6A का उपयोग करके 'प्रवासी मतदाता' के रूप में पंजीकरण कर सकते हैं। ✈️",
        "क्या गैर-नागरिक वोट दे सकते हैं?": "नहीं, केवल भारतीय नागरिक ही मतदान के पात्र हैं। 🇮🇳",
        "अपना मतदान केंद्र कैसे खोजें?": "electoralsearch.eci.gov.in पर खोजें या 1950 पर SMS करें। 📍",
        "मतदान के मानक घंटे?": "आमतौर पर सुबह 7:00 से शाम 6:00 बजे तक। ⏰",
        "मतदान केंद्र के अंदर की प्रक्रिया?": "1. पहचान जांच 2. स्याही और हस्ताक्षर 3. EVM बटन दबाएं 4. VVPAT पर्ची देखें। 🗳️",
        "अमिट स्याही क्या है?": "यह दोबारा मतदान रोकने के लिए आपकी उंगली पर लगाई जाने वाली बैंगनी स्याही है। ☝️",
        "EVM क्या है?": "इलेक्ट्रॉनिक वोटिंग मशीन सुरक्षित और छेड़छाड़-मुक्त तरीके से वोट रिकॉर्ड करती है। 🗳️",
        "VVPAT क्या है?": "VVPAT मशीन 7 सेकंड के लिए एक पर्ची दिखाती है जिससे आप अपने वोट की पुष्टि कर सकते हैं। ✅",
        "EVM पर वोट की पुष्टि?": "बीप की आवाज सुनें और EVM के पास VVPAT खिड़की में पर्ची देखें। 🧐",
        "यदि EVM खराब हो जाए?": "अधिकारी मशीन बदल देंगे। पिछले वोट सुरक्षित रहते हैं। 🛠️",
        "नोटा क्या है?": "यह आपको सभी उम्मीदवारों को अस्वीकार करने का विकल्प देता है। यह EVM पर अंतिम बटन है। 🚫",
        "चुनाव ड्यूटी कर्मचारी कैसे वोट दे सकते हैं?": "वे पोस्टल बैलेट या चुनाव ड्यूटी प्रमाण पत्र का उपयोग करते हैं। ✉️",
        "निविदा मत क्या है?": "यदि आपके नाम पर कोई और वोट दे चुका है, तो आप पहचान सिद्ध कर कागजी मतपत्र पर वोट दे सकते हैं। 📄",
        "चुनौतीपूर्ण मत क्या है?": "यदि कोई आपकी पहचान को चुनौती देता है, तो अधिकारी के सामने उसे सिद्ध करना होगा। ⚖️",
        "वरिष्ठ नागरिकों के लिए घर से वोट?": "85+ आयु के लोग फॉर्म 12D भरकर घर से वोट दे सकते हैं। 🏡",
        "वोटों की गिनती और परिणाम?": "गिनती सुरक्षित केंद्रों पर होती है और परिणाम चुनाव आयोग द्वारा लाइव अपलोड किए जाते हैं। 📊",
        "परिणामों के लाइव अपडेट?": "results.eci.gov.in पर देखें। 📱"
    },
    tamil: {
        "புதிய வாக்காளராக பதிவு செய்வது எப்படி?": "voters.eci.gov.in போர்ட்டலில் ஆன்லைனில் பதிவு செய்யவும். படிவம் 6-ஐப் பூர்த்தி செய்து ஆவணங்களைச் சமர்ப்பிக்கவும். 📝",
        "படிவம் 6 என்றால் என்ன?": "படிவம் 6 'புதிய வாக்காளர் பதிவு'க்கானது. உங்களுக்கு 18 வயது பூர்த்தியாகியிருந்தால் இதைப் பயன்படுத்தலாம். 🏠",
        "விண்ணப்ப நிலையை எவ்வாறு கண்காணிப்பது?": "voters.eci.gov.in-ல் உங்கள் குறிப்பு எண்ணைப் பயன்படுத்தி நிலையை அறியலாம். 🔍",
        "பதிவு செய்வதற்கான கடைசி தேதி?": "தேர்தல் அறிவிப்பு வரும் வரை விண்ணப்பிக்கலாம். ⏳",
        "படிவம் 8 ஐ எவ்வாறு நிரப்புவது?": "வாக்காளர் அட்டையில் திருத்தங்கள் செய்ய படிவம் 8-ஐப் பயன்படுத்தவும். ✏️",
        "படிவம் 7 என்றால் என்ன?": "வாக்காளர் பட்டியலில் இருந்து பெயரை நீக்க படிவம் 7-ஐப் பயன்படுத்தவும். ❌",
        "EPIC எண் என்றால் என்ன?": "EPIC என்பது உங்கள் 10 இலக்க வாக்காளர் அடையாள எண் ஆகும். 🆔",
        "வாக்காளர் அட்டை தொலைந்துவிட்டது?": "படிவம் 8 மூலம் மாற்று அட்டையைப் பெற விண்ணப்பிக்கலாம். 💳",
        "மின்-வாக்காளர் அட்டையை பதிவிறக்குவது?": "பதிவு செய்யப்பட்ட மொபைல் எண் இருந்தால் ஆன்லைனில் PDF-ஆக பதிவிறக்கலாம். 📱",
        "வாக்காளர் அட்டை ஒன்றுக்கும் மேற்பட்டதா?": "கூடாது. ஒன்றுக்கு மேற்பட்ட அடையாள அட்டைகளை வைத்திருப்பது சட்டப்படி குற்றம். 🚫",
        "வாக்காளர் அட்டை இல்லாவிட்டால் ஐடி?": "ஆதார், பான், பாஸ்போர்ட் உள்ளிட்ட 12 மாற்று ஆவணங்களைப் பயன்படுத்தலாம். 🪪",
        "ஆதார் அட்டை செல்லுபடியாகுமா?": "ஆம், வாக்களிக்க ஆதார் அட்டையைப் பயன்படுத்தலாம். 💳",
        "வாக்களிக்க குறைந்தபட்ச வயது?": "தகுதியான தேதியில் 18 வயது பூர்த்தியாகியிருக்க வேண்டும். 🎂",
        "வெளிநாடு வாழ் இந்தியர்கள் வாக்களிக்கலாமா?": "ஆம், படிவம் 6A மூலம் பதிவு செய்து நேரில் வந்து வாக்களிக்கலாம். ✈️",
        "குடிமகன் அல்லாதவர் வாக்களிக்கலாமா?": "இல்லை. இந்தியக் குடிமக்கள் மட்டுமே வாக்களிக்கத் தகுதியுடையவர்கள். 🇮🇳",
        "வாக்குச்சாவடியை எவ்வாறு கண்டுபிடிப்பது?": "electoralsearch.eci.gov.in-ல் தேடலாம் அல்லது 1950-க்கு SMS அனுப்பலாம். 📍",
        "வாக்குப்பதிவு நேரம் என்ன?": "பொதுவாக காலை 7:00 முதல் மாலை 6:00 மணி வரை. ⏰",
        "வாக்குச்சாவடிக்குள் நடைமுறை?": "1. அடையாளச் சரிபார்ப்பு 2. மை வைப்பது 3. பொத்தானை அழுத்துதல் 4. VVPAT சரிபார்ப்பு. 🗳️",
        "வாக்காளர் மை என்றால் என்ன?": "இரட்டை வாக்குகளைத் தவிர்க்க விரலில் வைக்கப்படும் அழியாத மை. ☝️",
        "EVM என்றால் என்ன?": "மின்னணு வாக்குப்பதிவு இயந்திரம் பாதுகாப்பானது மற்றும் நம்பகமானது. 🗳️",
        "VVPAT என்றால் என்ன?": "நீங்கள் யாருக்கு வாக்களித்தீர்கள் என்பதை 7 விநாடிகள் காகிதச் சீட்டில் காட்டும் இயந்திரம். ✅",
        "வாக்கு சரியான வேட்பாளருக்கு சென்றதா?": "EVM-ல் பீப் சத்தத்தைக் கேட்டு, VVPAT-ல் சீட்டைச் சரிபார்க்கவும். 🧐",
        "EVM பழுதானால்?": "அதிகாரிகள் இயந்திரத்தை மாற்றுவார்கள். உங்கள் வாக்கு பாதுகாப்பாக இருக்கும். 🛠️",
        "நோட்டா என்றால் என்ன?": "எந்த வேட்பாளருக்கும் விருப்பமில்லை என்றால் இந்த பொத்தானை அழுத்தலாம். 🚫",
        "தேர்தல் பணி ஊழியர்கள்?": "தபால் வாக்குகள் மூலம் அவர்கள் வாக்களிக்கலாம். ✉️",
        "டெண்டர் வாக்கு?": "உங்கள் பெயரில் வேறு யாராவது வாக்களித்திருந்தால், அடையாளத்தைச் சபித்து காகித வாக்கு மூலம் வாக்களிக்கலாம். 📄",
        "சவாலான வாக்கு?": "யாராவது உங்கள் அடையாளத்தைச் சந்தேகித்தால், அதிகாரியிடம் அதை நிரூபிக்க வேண்டும். ⚖️",
        "வீட்டிலிருந்து வாக்களிக்க வசதி?": "85 வயதுக்கு மேற்பட்டவர்கள் படிவம் 12D மூலம் வீட்டிலிருந்தே வாக்களிக்கலாம். 🏡",
        "வாக்குகள் எவ்வாறு எண்ணப்படுகின்றன?": "பாதுகாப்பான மையங்களில் எண்ணப்பட்டு தேர்தல் ஆணையத்தால் முடிவுகள் அறிவிக்கப்படும். 📊",
        "நேரலை முடிவுகள் எங்கே?": "results.eci.gov.in போர்ட்டலில் பார்க்கலாம். 📱"
    },
    malayalam: {
        "പുതിയ വോട്ടറായി രജിസ്റ്റർ ചെയ്യാം?": "voters.eci.gov.in വഴിയോ വോട്ടർ ഹെൽപ്പ് ലൈൻ ആപ്പ് വഴിയോ രജിസ്റ്റർ ചെയ്യാം. ഫോം 6 പൂരിപ്പിക്കുക. 📝",
        "ഫോം 6 എന്നാൽ എന്ത്?": "പുതിയ വോട്ടർ രജിസ്ട്രേഷനുള്ള ഫോമാണിത്. 🏠",
        "അപേക്ഷയുടെ നില?": "voters.eci.gov.in സന്ദർശിച്ച് റെഫറൻസ് ഐഡി ഉപയോഗിച്ച് പരിശോധിക്കാം. 🔍",
        "രജിസ്ട്രേഷനുള്ള സമയം?": "തിരഞ്ഞെടുപ്പ് പ്രഖ്യാപനം വരെ രജിസ്റ്റർ ചെയ്യാം. ⏳",
        "ഫോം 8 എങ്ങനെ?": "പേര്, വയസ്സ്, വിലാസം എന്നിവ തിരുത്താൻ ഫോം 8 ഉപയോഗിക്കുക. ✏️",
        "ഫോം 7 ആർക്കാണ്?": "വോട്ടർ പട്ടികയിൽ നിന്ന് പേര് നീക്കം ചെയ്യാൻ ഫോം 7 ഉപയോഗിക്കുന്നു. ❌",
        "EPIC നമ്പർ എവിടെ?": "വോട്ടർ ഐഡിയിലെ 10 അക്കങ്ങളുള്ള തിരിച്ചറിയൽ നമ്പറാണ് എപിക്. 🆔",
        "വോട്ടർ ഐഡി നഷ്ടപ്പെട്ടാൽ?": "ഫോം 8 വഴി ഡ്യൂപ്ലിക്കേറ്റ് കാർഡിനായി അപേക്ഷിക്കാം. 💳",
        "ഇ-വോട്ടർ ഐഡി ഡൗൺലോഡ്?": "രജിസ്റ്റർ ചെയ്ത മൊബൈൽ ഉണ്ടെങ്കിൽ ഓൺലൈനായി ഡൗൺലോഡ് ചെയ്യാം. 📱",
        "ഒന്നിലധികം വോട്ടർ ഐഡി?": "ഇല്ല, ഒന്നിലധികം വോട്ടർ ഐഡി കൈവശം വെക്കുന്നത് കുറ്റകരമാണ്. 🚫",
        "വോട്ടർ ഐഡി ഇല്ലെങ്കിൽ?": "ആധാർ, പാസ്‌പോർട്ട് ഉൾപ്പെടെ 12 രേഖകൾ വോട്ട് ചെയ്യാൻ ഉപയോഗിക്കാം. 🪪",
        "ആധാർ ഉപയോഗിക്കാമോ?": "അതെ, വോട്ട് ചെയ്യാൻ ആധാർ കാർഡ് ഉപയോഗിക്കാം. 💳",
        "വോട്ട് ചെയ്യാനുള്ള പ്രായം?": "18 വയസ്സ് തികഞ്ഞിരിക്കണം. 🎂",
        "പ്രവാസികൾക്ക് വോട്ട്?": "അതെ, ഫോം 6A വഴി രജിസ്റ്റർ ചെയ്ത് നേരിട്ട് വന്ന് വോട്ട് ചെയ്യാം. ✈️",
        "വിദേശികൾക്ക് വോട്ട്?": "ഇല്ല, ഇന്ത്യൻ പൗരന്മാർക്ക് മാത്രമേ വോട്ട് ചെയ്യാൻ അവകാശമുള്ളൂ. 🇮🇳",
        "പോളിംഗ് ബൂത്ത് കണ്ടെത്തൽ?": "electoralsearch.eci.gov.in വഴി കണ്ടെത്താം. 📍",
        "വോട്ടെടുപ്പ് സമയം?": "സാധാരണയായി രാവിലെ 7 മുതൽ വൈകിട്ട് 6 വരെ. ⏰",
        "ബൂത്തിലെ നടപടിക്രമങ്ങൾ?": "1. ഐഡി പരിശോധന 2. മഷി പുരട്ടൽ 3. ബട്ടൺ അമർത്തൽ 4. വിവിപാറ്റ് പരിശോധന. 🗳️",
        "മഷി എന്തിനാണ്?": "ഇരട്ട വോട്ട് തടയാൻ വിരലിൽ പുരട്ടുന്ന മായാത്ത മഷി. ☝️",
        "EVM എന്താണ്?": "വോട്ട് രേഖപ്പെടുത്തുന്ന ഇലക്ട്രോണിക് മെഷീൻ. 🗳️",
        "VVPAT എന്താണ്?": "വോട്ട് ചെയ്തത് ശരിയാണോ എന്ന് പരിശോധിക്കാൻ സഹായിക്കുന്ന സ്ലിപ്പ്. ✅",
        "വോട്ട് ഉറപ്പാക്കൽ?": "വിവിപാറ്റ് വിൻഡോയിൽ 7 സെക്കൻഡ് സ്ലിപ്പ് പരിശോധിക്കുക. 🧐",
        "മെഷീൻ കേടായാൽ?": "ഉദ്യോഗസ്ഥർ മെഷീൻ മാറ്റി നൽകും. വോട്ടുകൾ സുരക്ഷിതമായിരിക്കും. 🛠️",
        "എന്താണ് നോട്ട?": "സ്ഥാനാർത്ഥികളെ ആരെയും ഇഷ്ടമല്ലെങ്കിൽ വോട്ട് ചെയ്യാൻ ഈ ബട്ടൺ അമർത്താം. 🚫",
        "ഡ്യൂട്ടിയുള്ളവർക്ക്?": "പോസ്റ്റൽ ബാലറ്റ് വഴി അവർക്ക് വോട്ട് ചെയ്യാം. ✉️",
        "ടെൻഡർ വോട്ട്?": "മറ്റാരെങ്കിലും നിങ്ങളുടെ പേരിൽ വോട്ട് ചെയ്താൽ ഐഡി തെളിയിച്ച് പേപ്പർ ബാലറ്റ് ഉപയോഗിക്കാം. 📄",
        "ചലഞ്ച് വോട്ട്?": "ആരെങ്കിലും നിങ്ങളുടെ ഐഡി ചോദ്യം ചെയ്താൽ അത് ഉദ്യോഗസ്ഥന് മുന്നിൽ തെളിയിക്കണം. ⚖️",
        "വീട്ടിൽ വോട്ട്?": "85 വയസ്സു കഴിഞ്ഞവർക്കും ഭിന്നശേഷിക്കാർക്കും ഫോം 12D വഴി ഇതിന് സൗകര്യമുണ്ട്. 🏡",
        "വോട്ടെണ്ണൽ?": "സുരക്ഷിത കേന്ദ്രങ്ങളിൽ എണ്ണി ഫലം പ്രഖ്യാപിക്കും. 📊",
        "തത്സമയ ഫലങ്ങൾ?": "results.eci.gov.in സന്ദർശിക്കുക. 📱"
    }
};